### ISSUE TITLE
Compiling Enums with plexus-compiler-eclipse requires optimize=true

### ISSUE THREAD

**Issue by neonics** [sonatype/plexus-compiler#16]
Howdy,

The following code results in an error when using the eclipse compiler:

    class Foo {
        static enum MyEnum { A }

        void foo() {
            switch ( MyEnum.A ) { case A: }
        }
    }

The error is: 

    C:\code\mvn-eclipse-bug\src\main\java\foo\Foo.java:[6] Cannot switch on a value of type Foo.MyEnum. Only convertible int values, strings or enum variables are permitted

The pom used:

    <?xml version="1.0"?>

    <project>
      <modelVersion>4.0.0</modelVersion>
      <groupId>test</groupId>
      <version>1-SNAPSHOT</version>
      <artifactId>mvn-eclipse-bug</artifactId>

      <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <compilerId>eclipse</compilerId>
                    <source>1.6</source>
                    <target>1.6</target>
                    
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-compiler-eclipse</artifactId>
                        <version>2.3-SNAPSHOT</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>

      </build>
    </project>

Enabling the <optimize> fixes the error, since according to [1], this is required for
setting org.eclipse.jdt.core.compiler.compliance. 

[1] https://github.com/sonatype/plexus-compiler/blob/master/plexus-compilers/plexus-compiler-eclipse/src/main/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.java#L156

**Comment by md-5** [comment]
This was fixed in https://github.com/sonatype/plexus-compiler/commit/a4eaf073f832c5e546daca2beb0ddd8132f3c923

If you or someone else could close it that would be great!
