### ISSUE TITLE
plxeus-compiler-eclipse requires "optimize" to set compliance level

### ISSUE THREAD

**Issue by baron1405** [sonatype/plexus-compiler#22]
I spent a few hours trying to figure out why a switch on a string gave the strange error:

"Cannot switch on a value of type String. Only convertible int values, strings or enum variables are permitted"

It turns out that the plexus-compiler-eclipse does not set the Java compliance level unless the optimize flag is set to true. What does optimization have to do with the language compliance level? At a minimum, there should be a clear statement in the documentation that the optimize flag must be set.

Details:
- Java compliance level 1.7
- Effects all versions of the eclipse JDT compiler >= 3.8.0
- Only manifests itself when switching on strings. Other Java 1.7 constructs (e.g. diamond operator) do not exhibit the problem.

**Comment by md-5** [comment]
This was fixed in https://github.com/sonatype/plexus-compiler/commit/a4eaf073f832c5e546daca2beb0ddd8132f3c923

If you or someone else could close it that would be great!
